[workspace]
members = [ "protocol", "protocol/protocol_types", "protocol/protocol_data_types", "cli"]
exclude = [ "server", "client"]

[workspace.package]
version = "0.1.0"
authors = [ "Xenira" ]
license = "GPL-3.0"