[workspace]
members = [ "protocol", "protocol/protocol_types", "protocol/protocol_data_types"]
exclude = [ "server", "client", "cli"]

[workspace.package]
version = "0.1.0"
authors = [ "Xenira" ]
license = "GPL-3.0"