name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: Heroku
      url: https://github.com/Xenira/space3
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "space-cubed" #Must be unique in Heroku
          heroku_email: "l.sprengel@pm.me"
          justlogin: true
      - run: heroku container:login
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
      - run: docker build . -t space-cubed:web --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit
      - run: docker tag space-cubed:web docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
      - run: heroku container:push web -a space-cubed
      - run: heroku container:release web -a space-cubed
