name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: Heroku
      url: https://github.com/Xenira/space3
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "space-cubed" #Must be unique in Heroku
          heroku_email: "l.sprengel@pm.me"
          justlogin: true
      - run: heroku container:login
      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-registry
          key: docker-registry-buildkit-${{ hashFiles('Dockerfile') }}
      - run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: echo $GITHUB_REPOSITORY
      - run: docker build . -t space-cubed:web --cache-from=localhost:5000/space-cubed:web --build-arg BUILDKIT_INLINE_CACHE=1
      - run: docker tag space-cubed:web localhost:5000/space-cubed:web && docker push localhost:5000/space-cubed:web || true
      - run: docker tag space-cubed:web registry.heroku.com/space-cubed/web
      - run: docker push registry.heroku.com/space-cubed/web
      - run: heroku container:release web -a space-cubed
